#!/bin/bash

do_anchor=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address)

echo "Got anchor url: ${do_anchor}"

PORT=3219 OUTBOUND_IP=$do_anchor ~/go/bin/nirn-proxy
